### PR TITLE
Allow the fetching of emojis of join subreddits

### PR DESCRIPTION
**Pull request by PythonCoderAS**
praw-dev/praw#1130

### CODE REVIEW

**Comment by bboe** [comment]
While this works, what's the point of supporting this for a `+` type multireddit?

**Comment by PythonCoderAS** [comment]
This should negate the need for an assert statement. Although there isn't a reason that we can't just throw an `Exception` if the user attempts to use a `+` style multireddit

**Comment by bboe** [comment]
> This should negate the need for an assert statement. Although there isn't a reason that we can't just throw an Exception if the user attempts to use a + style multireddit

I think you're overthinking this a bit. I don't have any reason to this anyone would want to get the emoji for a multireddit. Until we have such a reason, it's not really something we need to do anything about. Reddit will already result in a bad request if someone attempts to do it, so there's no need for us to explicitly check for it.

**Comment by PythonCoderAS** [comment]
Therefore, I'm closing this PR.

**Pull request closed without merging**
